Update patch set 2
Patch Set 2: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates breakage in Google's internal tree.

Patchset creates breakage in AOSP.
  The following snippet of `make` output may point you in the right direction:
find: `src': No such file or directory
packages/apps/Phone/src/com/android/phone/InCallScreen.java:1764: cannot find symbol
symbol  : variable DIAL_MODIFIED_TO_USSD
location: class com.android.internal.telephony.Connection.DisconnectCause
        } else if (cause == Connection.DisconnectCause.DIAL_MODIFIED_TO_USSD) {
                                                      ^
packages/apps/Phone/src/com/android/phone/InCallScreen.java:1767: cannot find symbol
symbol  : variable DIAL_MODIFIED_TO_SS
location: class com.android.internal.telephony.Connection.DisconnectCause
...

If your patchset has a dependency in a separate project, please ensure that both changes are uploaded with the same Change-Id.

Patch-set: 2
Label: Code-Review=0
Label: Verified=-1