Update patch set 1
Patch Set 1: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates merge conflict in Google's internal tree.

Patchset creates breakage in AOSP.
  The following snippet of `make` output may point you in the right direction:
build/core/base_rules.mk:513: dalvik/dx/junit-tests/Android.mk: Module "dx-tests" has useless module tags: tests. It will be installed anyway.
build/core/base_rules.mk:513: libcore/Android.mk: Module "core-tests-hostdex" has useless module tags: tests. It will be installed anyway.
find: `src': No such file or directory
packages/apps/Phone/src/com/android/phone/MobileNetworkSettings.java:337: cannot find symbol
symbol  : variable NT_MODE_LTE_WCDMA
location: interface com.android.internal.telephony.Phone
                        || (modemNetworkMode > Phone.NT_MODE_LTE_WCDMA)) {
                                                    ^
packages/apps/Phone/src/com/android/phone/MobileNetworkSettings.java:405: cannot find symbol
...

If your patchset has a dependency in a separate project and you believe that this is the cause of the breakage, a reviewer can verify +1 and Deckard will remove the verify -1 shortly thereafter.

Patch-set: 1
Label: Code-Review=0
Label: Verified=-1