Update patch set 1
Patch Set 1: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates merge conflict in Google's internal tree.

Patchset creates breakage in AOSP.
  The following snippet of `make` output may point you in the right direction:
find: `src': No such file or directory
packages/apps/Phone/src/com/android/phone/ADNList.java:25: cannot find symbol
symbol  : class MSimConstants
location: package com.android.internal.telephony
import static com.android.internal.telephony.MSimConstants.SUB1;
                                            ^
packages/apps/Phone/src/com/android/phone/ADNList.java:25: static import only from classes and interfaces
import static com.android.internal.telephony.MSimConstants.SUB1;
^
...

If your patchset has a dependency in a separate project, please ensure that both changes are uploaded with the same Change-Id.

Patch-set: 1
Reviewer: Deckard Autoverifier <1006433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=0
Label: Verified=-1