Update patch set 3
Patch Set 3: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates merge conflict in AOSP.
  The following snippet of `git apply` output may point you in the right direction:
error: patch failed: AndroidManifest.xml:494
error: AndroidManifest.xml: patch does not apply


Patchset creates merge conflict in Google's internal tree.

If you wish to pursue this change, please rebase and upload a new patchset.

Patch-set: 3
Label: Code-Review=0
Label: Verified=-1